### ISSUE TITLE
Any plans for UniDic support?

### ISSUE THREAD

**Issue by fasiha** [hecomi/node-mecab-async#14]
I'm hacking together a UniDic-capable version of mecab-async, but I was wondering if you had any definitive plans to officially support UniDic? Thanks 🙇!

**Comment by hecomi** [comment]
I think using the custom command added in #10 supports unidic.
```js
var MeCab = new require('mecab-async')
  , mecab = new MeCab()
;
mecab.command = 'mecab -d PATH_TO_UNIDIC';
```
Or you can customize the default mecab command in `mecabrc` to use unidic.
Is it good for your use case?

**Comment by fasiha** [comment]
Thanks for responding! Yes, I had to customize the `command` and also change `parse` and `format`, since UniDic prints out seven tab-separated fields, in different order than IPADIC.

**Comment by hecomi** [comment]
I see!
Have you created the custom interface for the parser and the formatter?
If so, could you send me the pull request?

**Comment by hecomi** [comment]
Sorry for my late reply...
I added a option to customize parser for the result given by MeCab.
